name: outfut_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:

  flutter:
    sdk: flutter
  provider: ^6.1.1
  intl: ^0.18.1

  image: ^4.1.3
  # Core Firebase
  firebase_core: ^3.9.0
  firebase_core_web: ^2.10.0
  firebase_auth: ^5.3.4
  firebase_auth_web: ^5.8.7
  firebase_storage: ^12.3.7
  firebase_storage_web: ^3.6.13
  cloud_firestore: ^5.6.0
  cloud_firestore_web: ^4.4.0
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.3
  js: ^0.7.1
  http: ^1.1.0
  path_provider: ^2.1.1
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.0.0+2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.jpg
    - assets/images/launch_background.jpg
    - assets/images/google_g_logo.png
    - assets/images/launch_background.jpeg
