// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKKvoNotF_EjG6baVUxuPe3FNu3FB5kcc',
    appId: '1:533839323676:web:4f8b61a638b2bcc8a3b5d9',
    messagingSenderId: '533839323676',
    projectId: 'fyp-o-o-s-s',
    authDomain: 'fyp-o-o-s-s.firebaseapp.com',
    storageBucket: 'fyp-o-o-s-s.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-nc9yoO6VoqLh7KPfINPjIpNAlKQ3Cag',
    appId: '1:533839323676:android:8abe375e54e8e160a3b5d9',
    messagingSenderId: '533839323676',
    projectId: 'fyp-o-o-s-s',
    storageBucket: 'fyp-o-o-s-s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0R1QpgU58T2js00jT633zhQLt8jjQCdQ',
    appId: '1:533839323676:ios:c99a2ed47d3df700a3b5d9',
    messagingSenderId: '533839323676',
    projectId: 'fyp-o-o-s-s',
    storageBucket: 'fyp-o-o-s-s.firebasestorage.app',
    iosBundleId: 'com.example.outfut2',
  );

}